### ISSUE TITLE
Con las ultimas versiones de graphql tengo este error.

### ISSUE THREAD

**Issue by ghost** [pechitook/graphql-platzi#2]
`Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.`

No se como pueda solucionarlo. Podrias ayudarme ?

**Comment by pechitook** [comment]
¿Podrías poner el contenido de tu `package.json`? Tal vez, como dice el error, hay múltiples versiones de GraphQL instaladas. También podés probar borrando `node_modules` y reinstalando las dependencias.

**Comment by ghost** [comment]
Instale los paquetes:
`yarn add apollo-server-express body-parser express graphql graphql-tools`
Al instalar sale esto:
`warning "apollo-server-core@1.1.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.1".
warning "apollo-tracing@0.0.7" has incorrect peer dependency "graphql@^0.10.0".
warning "apollo-server-express@1.1.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.1".`

**package.json**
`  "dependencies": {
    "apollo-server-express": "^1.1.2",
    "babel-eslint": "^7.2.3",
    "body-parser": "^1.18.2",
    "casual": "^1.5.17",
    "express": "^4.15.5",
    "graphql": "^0.11.4",
    "graphql-tools": "^1.2.3",
    "knex": "^0.13.0",
    "objection": "^0.8.9",
    "sqlite3": "^3.1.12",
    "standard": "^10.0.2"
  },`
Pero ya no sale el error.
Muchas gracias. Por responder.
